#!/usr/bin/env python3

from pathlib import Path
import argparse
import imagetools


parser = argparse.ArgumentParser(description='resize image')
parser.add_argument('input', type=Path, help='provide input image path')
parser.add_argument('width', type=int, help='set desired width')
parser.add_argument('output', type=Path, help='provide output image path')

args = parser.parse_args()

imagetools.resize(args.input.read_bytes(), args.width, args.output)
