---

- name: install from source repo
  tags: [build, garage]
  include: >
    {{ shipyard }}/tasks/python/build.yml
    package_name=garage package_repo={{ garage_repo }}

- name: archive
  tags: [archive, garage]
  include: "{{ shipyard }}/tasks/python/archive.yml package_name=garage"
