---

- tags: [build, lxml]
  block:

    - name: install build dependencies
      apt: name={{ item }}
      with_items:
        - libxml2-dev
        - libxslt1-dev
      become: yes

    - name: install lxml
      command: "{{ cpython_pip }} install lxml"
      args:
        creates: "{{ cpython_site_packages }}/lxml-*"
      become: yes

- tags: [archive, lxml]
  block:

    - name: archive runtime libraries
      include: tasks/copy.yml
      args:
        path: /usr/lib/x86_64-linux-gnu
        dest: "{{ build_out }}"
        patterns:
          - libexslt.so*
          - libicudata.so*
          - libicuuc.so*
          - libstdc++.so*
          - libxml2.so*
          - libxslt.so*

    - name: archive lxml
      include: tasks/python/archive.yml package_name=lxml
