[package]
name = "g1_bytes_derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
heck.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
