---

- tags: [build, pyyaml]
  block:

    - name: install libyaml
      apt: name=libyaml-dev
      become: yes

    - name: install pyyaml
      command: "{{ cpython_pip }} install PyYAML"
      args:
        creates: "{{ cpython_site_packages }}/PyYAML-*"
      become: yes

- tags: [archive, pyyaml]
  block:

    - name: archive libyaml
      include: >
        {{ shipyard }}/tasks/copy.yml
        path=/usr/lib/x86_64-linux-gnu patterns=libyaml*.so*
        dest={{ build_out }}

    - name: archive pyyaml
      synchronize: src={{ cpython_site_packages }}
                   dest={{ build_out }}
      args:
        rsync_opts:
          - "--relative"
          - "--include 'PyYAML*'"
          - "--include '_yaml*'"
          - "--include 'yaml'"
          - "--exclude '{{ cpython_site_packages }}/*'"
      become: yes
