---

- tags: [build, pyyaml]
  block:

    - name: install libyaml
      apt: name=libyaml-dev
      become: yes

    - name: install pyyaml
      command: "{{ cpython_pip }} install PyYAML"
      args:
        creates: "{{ cpython_site_packages }}/PyYAML-*"
      become: yes

- tags: [archive, pyyaml]
  block:

    - name: archive libyaml
      include: tasks/copy.yml
               path=/usr/lib/x86_64-linux-gnu patterns=libyaml*.so*
               dest={{ build_out }}

    - name: archive pyyaml
      include: tasks/python/archive.yml package_name=PyYAML
