---

- tags: [build, cpython]
  block:

    - name: install mercurial
      apt: name=mercurial
      become: yes

    - name: install build dependencies
      apt: name={{ item }}
      with_items:
        - build-essential
        # Compression...
        - libbz2-dev
        - liblzma-dev
        - zlib1g-dev
        # Console...
        - libncursesw5-dev
        - libreadline-dev
        # Database...
        - libdb-dev
        - libgdbm-dev
        - libsqlite3-dev
        # Network...
        - libssl-dev
      become: yes

    - name: check out source repo
      hg: repo={{ cpython_repo }} version={{ cpython_version }}
          dest={{ cpython_build_src }}
          purge=yes

    - name: configure
      command: ./configure --prefix {{ cpython_prefix }} {{ cpython_configs }}
               chdir={{ cpython_build_src }}
               creates={{ cpython_build_src }}/Makefile

    - name: build
      command: make
               chdir={{ cpython_build_src }}
               creates={{ cpython_build_src }}/python

    - name: install
      command: make install
               chdir={{ cpython_build_src }}
               creates={{ cpython_python }}
      become: yes

    - name: link header directory
      file: path={{ cpython_include }}
            src=python{{ cpython_major }}.{{ cpython_minor }}{{ cpython_abi_flags }}
            state=link
      when: cpython_abi_flags != ""
      become: yes

- tags: [archive, cpython]
  block:

    - name: archive core runtime libraries
      synchronize: src={{ item }} dest={{ build_out }} rsync_opts=--relative
      with_items:
        - /lib/x86_64-linux-gnu
        - /lib64
      become: yes

    - name: archive cpython runtime libraries
      include: tasks/copy.yml
      args:
        path: /usr/lib/x86_64-linux-gnu
        dest: "{{ build_out }}"
        patterns:
          - libgdbm.so*
          - libgdbm_compat.so*
          - libpanelw.so*
          - libsqlite3.so*

    - name: archive cpython modules
      synchronize:
        src: "{{ cpython_lib }}"
        dest: "{{ build_out }}"
        rsync_opts:
          - "--relative"
          # Exclude idlelib, lib2to3, tkinter, and turtledemo.
          - "--exclude '{{ cpython_lib }}/idlelib'"
          - "--exclude '{{ cpython_lib }}/lib2to3'"
          - "--exclude '{{ cpython_lib }}/tkinter'"
          - "--exclude '{{ cpython_lib }}/turtledemo'"
          # Exclude tests.
          - "--exclude '{{ cpython_lib }}/ctypes/test'"
          - "--exclude '{{ cpython_lib }}/distutils/tests'"
          - "--exclude '{{ cpython_lib }}/sqlite3/test'"
          - "--exclude '{{ cpython_lib }}/test'"
          - "--exclude '{{ cpython_lib }}/unittest/test'"
      become: yes

    - name: archive cpython binaries
      include: tasks/copy.yml
               path={{ cpython_prefix }}/bin patterns=python{{ cpython_major }}*
               dest={{ build_out }}
