[package]
name = "g1_actor_attribute"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["visit", "visit-mut"] }

[dev-dependencies]
syn = { workspace = true, features = ["extra-traits"] }
