#!/usr/bin/env python3

"""Helper script that converts CodeGeneratorRequest to JSON (mostly for
   testing schema.pyx).
"""

import json
import sys

from capnptools.schema import CodeGeneratorRequest


def main():
    request = CodeGeneratorRequest(sys.stdin.buffer.read())
    print(json.dumps(request._asdict(), indent=4, sort_keys=True))


if __name__ == '__main__':
    main()
