[package]
name = "bt_dht_proto"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
rand.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_bytes.workspace = true

bt_base.workspace = true
bt_bencode.workspace = true
bt_serde.workspace = true
