[package]
name = "etcd_pubsub"
version.workspace = true
edition.workspace = true

[dependencies]
fasthash.workspace = true
futures.workspace = true
linkme.workspace = true # Required by g1_param.
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

g1_param.workspace = true
g1_tokio.workspace = true

etcd_client.workspace = true
