[package]
name = "g1_tokio"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1.68"
bytes = "1.4.0"
futures = "0.3.28"
tokio = { version = "1.28.2", features = ["full"] }

g1_base = { path = "../base" }

[dev-dependencies]
# examples/ncat
clap = { version = "4.3.1", features = ["derive"] }
bittorrent_mse = { path = "../../bittorrent/mse" }

[features]
test_harness = []
