[package]
name = "g1_tokio"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["tracing"] }

g1_base.workspace = true

# feature: icmp
libc = { workspace = true, optional = true }
nix = { workspace = true, features = ["uio"], optional = true }
g1_nix = { workspace = true, optional = true }

[dev-dependencies]
scopeguard.workspace = true

# examples
clap.workspace = true
g1_cli = { workspace = true, features = ["param", "tracing"] }

# examples/ncat
bittorrent_base = { workspace = true, features = ["param"] }
bittorrent_mse.workspace = true
bittorrent_peer.workspace = true
bittorrent_socket.workspace = true
bittorrent_utp.workspace = true

# examples/path-mtu
rand.workspace = true
tracing.workspace = true

[[example]]
name = "path-mtu"
required-features = ["icmp"]

[features]
icmp = ["dep:libc", "dep:nix", "dep:g1_nix"]
test_harness = []
