[package]
name = "g1_tokio"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["tracing"] }

g1_base.workspace = true

# feature: icmp
libc = { workspace = true, optional = true }
nix = { workspace = true, features = ["net", "uio"], optional = true }
g1_nix = { workspace = true, optional = true }

# feature: param
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
scopeguard.workspace = true
tokio = { workspace = true, features = ["test-util", "tracing"] }

# examples
clap.workspace = true
g1_cli = { workspace = true, features = ["param", "tracing"] }

# examples/ncat
bittorrent_base = { workspace = true, features = ["param"] }
bittorrent_mse.workspace = true
bittorrent_peer.workspace = true
bittorrent_socket.workspace = true
bittorrent_utp.workspace = true

# examples/path-mtu
rand.workspace = true
tracing.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
nix = { workspace = true, features = ["zerocopy"] }
g1_nix.workspace = true

[[example]]
name = "path-mtu"
required-features = ["icmp"]

[features]
icmp = ["dep:libc", "dep:nix", "dep:g1_nix"]
param = ["dep:serde"]
test_harness = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tokio_unstable)'] }
