[package]
name = "g1_tokio"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1.68"
bytes = "1.4.0"
tokio = { version = "1.28.2", features = ["full"] }

[dev-dependencies]
clap = { version = "4.3.1", features = ["derive"] }
