[package]
name = "g1_tokio"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1.68"
bytes = "1.4.0"
futures = "0.3.28"
tokio = { version = "1.28.2", features = ["full", "tracing"] }

g1_base = { path = "../base" }

# feature: icmp
libc = { version = "0.2.147", optional = true }
nix = { version ="0.26.2", features = ["uio"], optional = true }
g1_nix = { path = "../nix", optional = true }

[dev-dependencies]
# examples
clap = { version = "4.3.1", features = ["derive"] }
g1_cli = { path = "../cli", features = ["param", "tracing"] }

# examples/ncat
bittorrent_mse = { path = "../../bittorrent/mse" }
bittorrent_utp = { path = "../../bittorrent/utp" }

# examples/path-mtu
rand = "0.8.5"
tracing = "0.1.37"

[[example]]
name = "path-mtu"
required-features = ["icmp"]

[features]
icmp = ["dep:libc", "dep:nix", "dep:g1_nix"]
test_harness = []
