[package]
name = "g1_base"
version.workspace = true
edition.workspace = true

[dependencies]
g1_base_derive.workspace = true

# feature: collections_ext
hashbrown = { workspace = true, optional = true }

[dev-dependencies]
tokio.workspace = true
trybuild.workspace = true

[features]
collections_ext = ["dep:hashbrown"]
