[package]
name = "g1_base"
version.workspace = true
edition.workspace = true

[dependencies]
g1_base_derive = { path = "../base_derive" }

# feature: collections_ext
hashbrown = { version = "0.14.3", optional = true }

[dev-dependencies]
tokio = { version = "1.28.2", features = ["full"] }
trybuild = "1.0.80"

[features]
collections_ext = ["dep:hashbrown"]
