[package]
name = "g1_base"
version.workspace = true
edition.workspace = true

[dependencies]
g1_base_derive = { path = "../base_derive" }

[dev-dependencies]
tokio = { version = "1.28.2", features = ["full"] }
trybuild = "1.0.80"
