---

- tags: [build, pyv8]
  block:

    - name: check python version
      fail: msg="require python 3"
      when: cpython_major != 3

    # TODO: Replace this with git (now v8 is totally hosted in git).
    - name: install subversion
      apt: name=subversion
      become: yes

    - name: copy source repo
      # NOTE: Watch the trailing slash (rsync trivia).
      synchronize: src={{ pyv8_repo }}/ dest={{ pyv8_src }}

    # NOTE: `setup_linux_py3k.py` is locally patched version of
    # `setup.py` for building pyv8 in Python 3.

    - name: build
      command: "{{ cpython_python }} setup_linux_py3k.py build"
      args:
        chdir: "{{ pyv8_src }}"
        creates: "{{ pyv8_src }}/build"

    - name: install
      command: "{{ cpython_python }} setup_linux_py3k.py install"
      args:
        chdir: "{{ pyv8_src }}"
        creates: "{{ cpython_site_packages }}/PyV8-*"
      become: yes

- tags: [archive, pyv8]
  block:

    - name: archive pyv8
      include: roles/cpython/tasks/archive-site-packages.yml
