---

- tags: [build, pyv8]
  block:

    - name: check python version
      fail: msg="require python 3"
      when: cpython_major != 3

    # TODO: Replace this with git (now v8 is totally hosted in git).
    - name: install subversion
      apt: name=subversion
      become: yes

    # NOTE: `setup_linux_py3k.py` is locally patched version of
    # `setup.py` for building pyv8 in Python 3.

    - name: install from source repo
      include: tasks/python/build.yml
               package_name=PyV8
               package_repo={{ pyv8_repo }}
               package_build={{ pyv8_build }}
               package_setup={{ pyv8_setup }}

- name: archive
  tags: [archive, pyv8]
  include: tasks/python/archive.yml package_name=PyV8
