[package]
name = "g1_param"
version.workspace = true
edition.workspace = true

[dependencies]
lazy-regex.workspace = true
linkme.workspace = true
regex.workspace = true # Override the version set by lazy-regex.
serde = { workspace = true, features = ["derive"] }
serde_yaml.workspace = true

[dev-dependencies]
clap.workspace = true
