[package]
name = "g1_param"
version.workspace = true
edition.workspace = true

[dependencies]
lazy-regex = "3.1.0"
linkme = "0.3.10"
regex = "1.10.3" # Override the version set by lazy-regex.
serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.96", features = ["raw_value"] }

[dev-dependencies]
clap = { version = "4.3.1", features = ["derive"] }
