#!/usr/bin/env python3

"""List dependencies and their (latest) version in Maven repo.

You may use this as a guide to upgrade third-party packages.
"""

from garage import apps
from garage.partdefs.http import clients


DEPS = [
    'args4j:args4j',

    'org.capnproto:runtime',

    'com.google.dagger:dagger',
    'com.google.dagger:dagger-compiler',

    'com.google.code.findbugs:jsr305',

    'com.google.guava:guava',

    'net.java.dev.jna:jna',

    'org.jooq:jooq',
    'org.jooq:jooq-codegen',

    'org.junit.jupiter:junit-jupiter-api',
    'org.junit.jupiter:junit-jupiter-engine',
    'org.junit.platform:junit-platform-gradle-plugin',

    'org.apache.lucene:lucene-core',
    'org.apache.lucene:lucene-queryparser',

    'org.slf4j:slf4j-api',
    'org.slf4j:slf4j-simple',

    'org.yaml:snakeyaml',

    'org.xerial:sqlite-jdbc',
]


URL_BASE = 'https://mvnrepository.com/artifact/'


@apps.with_argument(
    '--latest', type=int, default=2,
    help='show latest N versions (default to %(default)s)',
)
def main(args, client: clients.PARTS.client):
    for pkg in DEPS:
        response = client.get(URL_BASE + pkg.replace(':', '/'))
        doc = response.dom()
        elements = (
            doc.xpath('//a[@class="vbtn release"]') or
            doc.xpath('//a[@class="vbtn milestone"]')
        )
        if elements:
            versions = ', '.join(e.text for e in elements[:args.latest])
        else:
            versions = '?'
        print('%-60s %s' % (pkg, versions))
    return 0


if __name__ == '__main__':
    apps.run(main)
