[package]
name = "g1_html_macro"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
lazy-regex.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
syn = { workspace = true, features = ["extra-traits"] }
