[package]
name = "g1_reqwest"
version.workspace = true
edition.workspace = true

[dependencies]
regex.workspace = true
reqwest = { workspace = true, features = ["brotli", "deflate", "gzip", "socks", "zstd"] }
serde = { workspace = true, features = ["derive"] }
url = { workspace = true, features = ["serde"] } # Enable additional features for reqwest.

# For now, we are only using `g1_param::parse`, so we do not need to add `linkme` to the
# dependencies.
g1_param.workspace = true

[dev-dependencies]
clap.workspace = true
linkme.workspace = true # Required by g1_param.
tokio.workspace = true
g1_cli = { workspace = true, features = ["param", "tracing"] }
