[package]
name = "bittorrent_tracker"
version.workspace = true
edition.workspace = true

[dependencies]
percent-encoding = "2.3.0"
rand = "0.8.5"
snafu = "0.7.4"

bittorrent_base = { path = "../base" }
bittorrent_metainfo = { path = "../metainfo" }

[dev-dependencies]
hex-literal = "0.4.1"

bittorrent_metainfo = { path = "../metainfo", features = ["test_harness"] }
