[package]
name = "bittorrent_udp"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
linkme.workspace = true # Required by g1_param.

g1_futures.workspace = true
g1_param.workspace = true
