[workspace]
members = [
    "bittorrent/actor",
    "bittorrent/base",
    "bittorrent/bencode",
    "bittorrent/dht",
    "bittorrent/extension",
    "bittorrent/manager",
    "bittorrent/metainfo",
    "bittorrent/mse",
    "bittorrent/peer",
    "bittorrent/socket",
    "bittorrent/storage",
    "bittorrent/tracker",
    "bittorrent/trackerless",
    "bittorrent/transceiver",
    "bittorrent/udp",
    "bittorrent/utp",
    "g1/base",
    "g1/base_derive",
    "g1/bytes",
    "g1/bytes_derive",
    "g1/cli",
    "g1/futures",
    "g1/msg",
    "g1/nix",
    "g1/param",
    "g1/serde",
    "g1/tokio",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
