[workspace]
members = [
    "g1/base",
    "g1/base_derive",
    "g1/bytes",
    "g1/bytes_derive",
    "g1/param",
    "g1/tokio",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
