---

- tags: [build, boost]
  block:

    - name: install build dependencies
      apt: name=build-essential
      become: yes

    - name: create build directories
      file: path={{ item }} state=directory
      with_items:
        - "{{ boost_build_root }}"
        - "{{ boost_build_dir }}"

    - name: download source tarball
      get_url: url={{ boost_tarball_url }} dest={{ boost_tarball }}
               checksum={{ boost_tarball_checksum }}

    # NOTE: Too bad `unarchive` module cannot handle Boost's tarball :(
    - name: unarchive source tarball
      command: tar xjf {{ boost_tarball }}
               chdir={{ boost_build_root }}
               creates={{ boost_build_src }}

    - name: configure
      command: ./bootstrap.sh --prefix={{ boost_prefix }} {{ boost_configs }}
               chdir={{ boost_build_src }}
               creates={{ boost_build_src }}/project-config.jam

    # Unfortunately b2 cannot separate build and install step :(
    - name: build and install
      command: ./b2 --build-dir={{ boost_build_dir }}
                    variant=release
                    link=shared
                    threading=multi
                    runtime-link=shared
                    install
               chdir={{ boost_build_src }}
               creates={{ boost_build_dir }}/boost
      become: yes

- tags: [archive, boost]
  block:

    - name: archive c++ runtime libraries
      include: tasks/copy.yml
               path=/usr/lib/x86_64-linux-gnu patterns=libstdc++.so*
               dest={{ build_out }}

    - name: archive boost runtime libraries
      include: tasks/copy.yml
               path={{ boost_prefix }}/lib patterns=libboost*
               dest={{ build_out }}
