[package]
name = "dkvcached"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
futures.workspace = true
tokio.workspace = true
tracing.workspace = true

g1_cli = { workspace = true, features = ["param", "tracing"] }

dkvcache_server.workspace = true
