[package]
name = "ddcache_server"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
capnp.workspace = true
futures.workspace = true
linkme.workspace = true # Required by g1_param.
rand.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid = { workspace = true, features = ["fast-rng", "serde", "v4"] }
zmq.workspace = true

g1_base.workspace = true
g1_param.workspace = true
g1_tokio.workspace = true
g1_zmq.workspace = true

ddcache_rpc.workspace = true
ddcache_storage.workspace = true
