[package]
name = "g1_cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true

# feature: param
g1_param = { workspace = true, optional = true }

# feature: tracing
console-subscriber = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }

[features]
param = ["dep:g1_param"]
tracing = ["dep:console-subscriber", "dep:tracing-subscriber"]
