[package]
name = "g1_cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true

# feature: param
serde_yaml = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
g1_param = { workspace = true, optional = true }
g1_yaml = { workspace = true, optional = true }

# feature: tracing
console-subscriber = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }

[features]
param = ["dep:serde_yaml", "dep:tracing", "dep:g1_param", "dep:g1_yaml"]
tracing = ["dep:console-subscriber", "dep:tracing-subscriber"]
