[package]
name = "g1_nix"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
libc.workspace = true
nix.workspace = true

[dev-dependencies]
hex-literal.workspace = true
