[package]
name = "g1_chrono"
version.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true

g1_base.workspace = true

# feature: serde
serde = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }

[features]
serde = ["dep:serde", "dep:serde_with"]
