[package]
name = "ddcache_rpc"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
capnp.workspace = true
chrono.workspace = true
fasthash.workspace = true
linkme.workspace = true # Required by g1_param.
serde = { workspace = true, features = ["derive"] }
snafu.workspace = true
uuid.workspace = true

etcd_client.workspace = true
etcd_pubsub.workspace = true
g1_capnp.workspace = true
g1_param.workspace = true
g1_zmq.workspace = true

[build-dependencies]
capnpc.workspace = true

[dev-dependencies]
# examples/ddcache-proto
clap.workspace = true
tokio.workspace = true
zmq.workspace = true
g1_cli = { workspace = true, features = ["param", "tracing"] }

ddcache_client_raw.workspace = true
