[package]
name = "ddcache_client_service"
version.workspace = true
edition.workspace = true

[dependencies]
futures.workspace = true
snafu.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

etcd_pubsub.workspace = true
g1_base = { workspace = true, features = ["collections_ext"] }
g1_tokio.workspace = true

ddcache_client_raw.workspace = true
ddcache_rpc.workspace = true
