[package]
name = "g1_url_derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
syn = { workspace = true, features = ["extra-traits"] }
