[package]
name = "bittorrent_storage"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1.73"
bitvec = "1.0.1"
bytes = "1.4.0"
snafu = "0.7.4"
tokio = { version = "1.28.2", features = ["full"] }

bittorrent_base = { path = "../base" }
