[package]
name = "g1_futures"
version.workspace = true
edition.workspace = true

[dependencies]
futures.workspace = true
tracing.workspace = true

g1_base.workspace = true

[dev-dependencies]
tokio.workspace = true
