#!/usr/bin/env python3

from argparse import ArgumentParser
from pathlib import Path
from subprocess import check_call
from tempfile import TemporaryDirectory


# 1. Install minimum runtime dependencies of the ops package
# 2. Add user plumber and grant him password-less sudo
# 3. Add group rkt and rkt-admin to user plumber
DOCKERFILE = '''\
FROM {base_image}

RUN apt-get update \\
 && apt-get install --yes python3 sudo wget \\
 && adduser --disabled-password --gecos "" plumber \\
 && echo "plumber ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/99-plumber \\
 && chmod 440 /etc/sudoers.d/99-plumber \\
 && groupadd --force --system rkt-admin \\
 && groupadd --force --system rkt \\
 && usermod --append --groups rkt-admin,rkt plumber

USER plumber
WORKDIR /home/plumber
CMD ["/bin/bash"]
'''


def main():
    parser = ArgumentParser(description="""Make tester Docker image.""")
    parser.add_argument(
        '--base-image', required=True, help="""set base Docker image""")
    parser.add_argument('output', help="""set the tag of the tester image""")
    args = parser.parse_args()
    with TemporaryDirectory() as build_dir:
        build_dir = Path(build_dir)
        (build_dir / 'Dockerfile').write_text(
            DOCKERFILE.format(base_image=args.base_image))
        cmd = ['docker', 'build', '--tag', args.output, str(build_dir)]
        print('execute: %s' % ' '.join(cmd))
        check_call(cmd)


if __name__ == '__main__':
    main()
