#!/usr/bin/env python3

from argparse import ArgumentParser
from pathlib import Path
from subprocess import check_call
from tempfile import TemporaryDirectory


# 1. Add group rkt to user plumber (for rkt).
# 2. Install runtime dependencies of the ops package.
DOCKERFILE = '''\
FROM {base_image}

RUN sudo groupadd --force --system rkt-admin \\
 && sudo groupadd --force --system rkt \\
 && sudo usermod --append --groups rkt-admin,rkt plumber \\
 && sudo apt-get install --yes python3 wget
'''


def main():
    parser = ArgumentParser(description="""Make tester Docker image.""")
    parser.add_argument('--base-image', required=True,
                        help="""set base image""")
    parser.add_argument('output', help="""set the tag of the tester image""")
    args = parser.parse_args()
    with TemporaryDirectory() as build_dir:
        build_dir = Path(build_dir)
        # Path.write_text is defined in Python 3.5 :(
        with (build_dir / 'Dockerfile').open('w') as dockerfile:
            dockerfile.write(DOCKERFILE.format(base_image=args.base_image))
        cmd = ['docker', 'build', '--tag', args.output, str(build_dir)]
        print('execute: %s' % ' '.join(cmd))
        check_call(cmd)


if __name__ == '__main__':
    main()
