[package]
name = "g1_msg"
version.workspace = true
edition.workspace = true

[dependencies]
futures = "0.3.28"
linkme = "0.3.10" # Required by g1_param.
snafu = "0.7.4"
tokio = { version = "1.28.2", features = ["full"] }
tracing = "0.1.37"

g1_param = { path = "../param" }
g1_tokio = { path = "../tokio" }

[dev-dependencies]
# examples
clap = { version = "4.3.1", features = ["derive"] }
g1_cli = { path = "../cli", features = ["param", "tracing"] }

# examples/udp-echo
g1_base = { path = "../base" }
