[package]
name = "g1_msg"
version.workspace = true
edition.workspace = true

[dependencies]
futures.workspace = true
linkme.workspace = true # Required by g1_param.
snafu.workspace = true
tokio.workspace = true
tracing.workspace = true

g1_param.workspace = true
g1_tokio.workspace = true

[dev-dependencies]
# examples
clap.workspace = true
g1_cli = { workspace = true, features = ["param", "tracing"] }

# examples/udp-echo
g1_base.workspace = true
