[package]
name = "g1_msg"
version.workspace = true
edition.workspace = true

[dependencies]
futures.workspace = true
tokio.workspace = true
tracing.workspace = true

g1_actor.workspace = true
g1_base = { workspace = true, features = ["collections_ext"] }
g1_tokio.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

# examples
bytes.workspace = true
clap.workspace = true
g1_cli = { workspace = true, features = ["param", "tracing"] }
