#!/usr/bin/env python3

from argparse import ArgumentParser
from pathlib import Path
from subprocess import check_call
from tempfile import TemporaryDirectory


# Add user `plumber` and grant password-less sudo to him.
DOCKERFILE = '''\
FROM {base_image}

RUN apt-get update \\
 && apt-get --yes full-upgrade \\
 && apt-get --yes install sudo \\
 && adduser --disabled-password --gecos "" plumber \\
 && echo "plumber ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/99-plumber \\
 && chmod 440 /etc/sudoers.d/99-plumber

USER plumber
WORKDIR /home/plumber
CMD ["/bin/bash"]
'''


def main():
    parser = ArgumentParser(description="""Make base builder Docker image.""")
    parser.add_argument(
        '--base-image', required=True, help="""set base Docker image""")
    parser.add_argument('output', help="""set the tag of the builder image""")
    args = parser.parse_args()
    with TemporaryDirectory() as build_dir:
        build_dir = Path(build_dir)
        (build_dir / 'Dockerfile').write_text(
            DOCKERFILE.format(base_image=args.base_image))
        cmd = ['docker', 'build', '--tag', args.output, str(build_dir)]
        print('execute: %s' % ' '.join(cmd))
        check_call(cmd)


if __name__ == '__main__':
    main()
