#!/usr/bin/env python3

"""Launch build process in a container."""

from pathlib import Path
import datetime
import sys

ROOT = Path(__file__).absolute().parent.parent.parent
sys.path.append(str(ROOT / 'py' / 'garage'))
sys.path.append(str(ROOT / 'py' / 'startup'))

from garage import apps
from garage import scripts


with_common_arguments = apps.with_decorators(
    apps.with_argument(
        '--build-name',
        help='set build container name',
    ),
    apps.with_argument(
        '--builder', required=True,
        help='set builder image',
    ),
    apps.with_argument(
        '--env-var', metavar='NAME=VALUE', action='append',
        help='add environment variable',
    ),
    apps.with_argument(
        '--volume', action='append',
        help='add data volume',
    ),
    apps.with_argument(
        '--preserve-container', action='store_true',
        help='do not remove container on exit',
    ),
)


def add_environment_variables(cmd, args):
    if args.env_var:
        for pair in args.env_var:
            cmd.append('--env')
            cmd.append(pair)
    return cmd


@apps.with_help('run builder interactively')
@with_common_arguments
def run(args, builder, cmd):
    """Run an interactive session in a builder container."""
    add_environment_variables(cmd, args)
    cmd.extend(['--interactive', '--tty', builder, '/bin/bash'])
    scripts.execute(cmd)
    return 0


# While you could do `--foreman=--path=/some/path`, for convenience, we
# denormalize --path, --parameter, and rule argument of foreman.
@apps.with_help('execute build rules')
@with_common_arguments
@apps.with_argument(
    '--path', action='append', help='add foreman search path')
@apps.with_argument(
    '--parameter', action='append', help='add parameter to foreman')
@apps.with_argument(
    '--foreman', action='append', help='send argument to foreman')
@apps.with_argument(
    # Split the whole path into two parts so that symlinks from/to
    # within INPUT_ROOT still work.
    '--input', metavar=('ROOT', 'PATH'), nargs=2,
    help='set input path at ROOT/PATH')
@apps.with_argument(
    '--output', help='set output directory path')
@apps.with_argument(
    'rule', nargs='+', help='add build rule')
def build(args, builder, cmd):
    """Execute one or more build rules."""
    add_environment_variables(cmd, args)
    if args.input:
        cmd.extend([
            '--volume',
            '%s:/home/plumber/input:ro' % Path(args.input[0]).resolve(),
        ])
    if args.output:
        output = Path(args.output).resolve()
        cmd.extend(['--volume', '%s:/home/plumber/output:rw' % output])
    cmd.extend([
        builder,
        '/home/plumber/garage/shipyard/scripts/foreman.sh', 'build',
    ])
    if args.input:
        cmd.extend([
            '--parameter',
            '//base:input=/home/plumber/input/%s' % args.input[1],
        ])
    for path in args.path or ():
        cmd.extend(['--path', path])
    for parameter in args.parameter or ():
        cmd.extend(['--parameter', parameter])
    cmd.extend(args.foreman or ())
    cmd.extend(args.rule)
    scripts.execute(cmd)
    return 0


@apps.with_argument(
    '--dry-run', action='store_true', help='do not really launch containers')
@apps.with_apps('action', 'builder action', run, build)
def main(args):
    with scripts.dry_run(args.dry_run):
        # Construct build name
        build_name = args.build_name
        if not build_name:
            build_name = 'build-%d' % int(datetime.datetime.now().timestamp())
        # Construct common part of the `docker run` command
        scripts.ensure_directory(ROOT / '.git')
        cmd = [
            'docker', 'run',
            '--name', build_name,
            '--volume', '%s:/home/plumber/garage:ro' % ROOT,
        ]
        for volume in args.volume or ():
            cmd.extend(['--volume', volume])
        # Execute the action
        status = args.action(args, builder=args.builder, cmd=cmd)
        if not args.preserve_container:
            # Don't remove builder on crash so that you may examine it
            scripts.execute(['docker', 'rm', build_name])
        return status


if __name__ == '__main__':
    apps.run(main)
